apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  labels:
    app: my-api
  annotations:
    git/commit-sha: fc59f4b55eb6b1e7ae0e3dc588d64687bf326e02
    git/author: t-kiattisak
    git/build-url: https://github.com/t-kiattisak/my-port/actions/runs/28714933933
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
  template:
    metadata:
      labels:
        app: my-api
    spec:
      containers:
        - name: web
          image: tkiattisakj9/my-port-api:fc59f4b55eb6b1e7ae0e3dc588d64687bf326e02 # ดึงภาพจาก Docker Hub ของคุณ
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
