apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ดึง Base manifest
  - ../../base/my-api

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: my-api

# ตัวอย่างการกำหนด ConfigMap เฉพาะตัวแปรบน Environment Production
configMapGenerator:
  - name: my-api-config
    literals:
      - APP_ENV=production
      - API_URL=https://api.example.com
