apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    # Git generator: Scans directory structure in Git and generates Argo CD Applications
    - git:
        repoURL: https://github.com/t-kiattisak/argo.git
        revision: HEAD
        directories:
          - path: apps/overlays/* # ค้นหา Application ทั้งหมดภายใต้โฟลเดอร์ overlays
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/t-kiattisak/argo.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
