apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager
  - ingress-nginx
  - external-secrets
  # - sealed-secrets # เปิดใช้งานเมื่อต้องการใช้ Sealed Secrets แทน External Secrets
